name: Build Frp

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          
      - run: |
          # https://github.com/actions/setup-go/issues/107
          git clone --depth=1 https://github.com/84896150/frp.git
          # cp -f `which go` /usr/bin/go
          ls
      - name: Make All
        run: |
          cd frp
          go mod tidy
          chmod u+x package.sh
          ./package.sh
          ls -x
          tar -czvf myetc.tar.gz release
          mkdir -p /opt/images
          sudo mv -f /home/runner/work/Frp-build/Frp-build/frp/myetc.tar.gz /opt/images/
      - name : Upload packages
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: Frp-packages
          path: /opt/images/
      
