name: Build Frp

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0    
    
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
          
      - run: | 
      git clone --depth=1 https://github.com/84896150/frp.git /home/runner/go/src/github.com/fatedier/frp
      cp -f `which go` /usr/bin/go
    - name: Build Firmware
      env:
        TNAME: frp
      run: |
        cd /home/runner/go/src/github.com/fatedier/frp
        #编译当前平台
        #make
        #ls -l
        #tar -czvf myetc.tar.gz bin
        make -f Makefile.cross-compiles
        #ls -l release
        tar -czvf myetc.tar.gz release
        mkdir -p /opt/images
        sudo mv -f /home/runner/go/src/github.com/fatedier/frp/myetc.tar.gz /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Frp-packages
        path: /opt/images/
