name: Build Frp

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
         go-version: '^1.13.1' # The Go version to download (if necessary) and use.
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install bison ed gawk gcc libc6-dev make       
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/fatedier/frp.git /home/runner/go/src/github.com/fatedier/frp
    - name: Build Firmware
      env:
        TNAME: K2P-5.0
      run: |
        cd /home/runner/go/src/github.com/fatedier/frp
        make
         ls -l
        tar -czvf myetc.tar.gz bin
        make -f Makefile.cross-compiles
        mkdir -p /opt/images
        sudo mv -f /home/runner/go/src/github.com/fatedier/frp/myetc.tar.gz /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Frp-packages
        path: /opt/images/
