name: Build Frp

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
          
      - run: |
          # https://github.com/actions/setup-go/issues/107
          git clone --depth=1 https://github.com/84896150/frp.git
          pwd
          ls -l
          cd frp
          ls -l
          cp -f `which go` /usr/bin/go
      - name: Make All
        run: |
          pwd
          cd frp
          ls -l
          chmod u+x package.sh
          ./package.sh
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --release-notes=./Release.md
        env:
          GITHUB_TOKEN: ${{ secrets.GPR_TOKEN }}
