#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Frp

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install bison ed gawk gcc libc6-dev make 
        wget https://www.golangtc.com/static/go/1.9.2/go1.9.2.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf go1.9.2.linux-amd64.tar.gz
        sed -i 'export PATH=$PATH:/usr/local/go/bin export GOPATH=/usr/local/gopath' /etc/profile
        sudo source /etc/profile         
        
    - name: Clone source code
      run: |
        sudo go get github.com/fatedier/frp
    - name: Build Firmware
      env:
        TNAME: K2P-5.0
      run: |
        cd /usr/local/gopath/src/github.com/fatedier/frp/
        make -f Makefile.cross-compiles
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Frp-packages
        path: /opt/images
